CREATE DATABASE SyncContact

USE [SyncContact]
GO

/****** Object:  Table [dbo].[ContactLog]    Script Date: 15/05/2014 8:29:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ContactLog](
	[ContactID] [nvarchar](max) NOT NULL,
	[DisplayName] [nvarchar](200) NOT NULL,
	[Alias] [nvarchar](max) NULL,
	[AssistantName] [nvarchar](200) NULL,
	[Birthday] [datetime] NULL,
	[BusinessAddressCity] [nvarchar](200) NULL,
	[BusinessAddressCountryOrRegion] [nvarchar](200) NULL,
	[BusinessAddressPostalCode] [nvarchar](200) NULL,
	[BusinessAddressState] [nvarchar](200) NULL,
	[BusinessFax] [nvarchar](110) NULL,
	[BusinessHomePage] [nvarchar](110) NULL,
	[BusinessPhone] [nvarchar](110) NULL,
	[BusinessPhoneTwo] [nvarchar](110) NULL,
	[CallBack] [nvarchar](50) NULL,
	[CarPhone] [nvarchar](110) NULL,
	[Children] [varchar](300) NULL,
	[Companies] [nvarchar](350) NULL,
	[CompanyMainPhone] [nvarchar](110) NULL,
	[CompanyName] [nvarchar](350) NULL,
	[CompleteName] [nvarchar](350) NULL,
	[ContactSource] [nvarchar](250) NULL,
	[Department] [nvarchar](250) NULL,
	[DirectoryId] [nvarchar](max) NULL,
	[DirectReports] [nvarchar](max) NULL,
	[EmailAddress1] [nvarchar](max) NULL,
	[EmailAddress2] [nvarchar](max) NULL,
	[EmailAddress3] [nvarchar](max) NULL,
	[EmailAddresses] [nvarchar](max) NULL,
	[FileAs] [nvarchar](max) NULL,
	[FileAsMapping] [nvarchar](max) NULL,
	[Generation] [nvarchar](250) NULL,
	[GivenName] [nvarchar](250) NULL,
	[HasPicture] [nvarchar](max) NULL,
	[HomeAddressCity] [nvarchar](200) NULL,
	[HomeAddressCountryOrRegion] [nvarchar](200) NULL,
	[HomeAddressPostalCode] [nvarchar](110) NULL,
	[HomeAddressState] [nvarchar](30) NULL,
	[HomeAddressStreet] [nvarchar](200) NULL,
	[HomeFax] [nvarchar](110) NULL,
	[HomePhone] [nvarchar](110) NULL,
	[HomePhone2] [nvarchar](110) NULL,
	[ImAddress1] [nvarchar](250) NULL,
	[ImAddress2] [nvarchar](250) NULL,
	[ImAddress3] [nvarchar](250) NULL,
	[ImAddresses] [nvarchar](200) NULL,
	[Isdn] [nvarchar](max) NULL,
	[JobTitle] [nvarchar](400) NULL,
	[Manager] [nchar](200) NULL,
	[ManagerMailbox] [nvarchar](200) NULL,
	[MiddleName] [nvarchar](200) NULL,
	[Mileage] [nvarchar](50) NULL,
	[MobilePhone] [nvarchar](110) NULL,
	[NickName] [nvarchar](200) NULL,
	[Notes] [nvarchar](max) NULL,
	[OfficeLocation] [nvarchar](200) NULL,
	[OtherAddressCity] [nvarchar](200) NULL,
	[OtherAddressCountryOrRegion] [nvarchar](200) NULL,
	[OtherAddressPostalCode] [nvarchar](110) NULL,
	[OtherAddressState] [nvarchar](50) NULL,
	[OtherFax] [nvarchar](110) NULL,
	[OtherTelephone] [nvarchar](110) NULL,
	[Pager] [nvarchar](500) NULL,
	[PhoneNumbers] [nvarchar](110) NULL,
	[PhoneticFirstName] [nvarchar](200) NULL,
	[PhoneticFullName] [nvarchar](200) NULL,
	[PhoneticLastName] [nvarchar](200) NULL,
	[Photo] [nvarchar](max) NULL,
	[PhysicalAddresses] [nvarchar](max) NULL,
	[PhysicalAddressIndex] [nvarchar](max) NULL,
	[PrimaryPhone] [nvarchar](110) NULL,
	[Profession] [nvarchar](200) NULL,
	[RadioPhone] [nvarchar](110) NULL,
	[SpouseName] [nvarchar](200) NULL,
	[Surname] [nvarchar](200) NULL,
	[Telex] [nvarchar](50) NULL,
	[TtyTddPhone] [nvarchar](50) NULL,
	[WeddingAnniversary] [datetime] NULL,
	[ActionDate] [datetime] NULL,
	[Action] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO 

CREATE TABLE [dbo].[Contacts](
	[ContactID] [nvarchar](max) NOT NULL,
	[DisplayName] [nvarchar](300) NOT NULL,
	[Alias] [nvarchar](max) NULL,
	[AssistantName] [nvarchar](200) NULL,
	[Birthday] [datetime] NULL,
	[BusinessAddressCity] [nvarchar](200) NULL,
	[BusinessAddressCountryOrRegion] [nvarchar](200) NULL,
	[BusinessAddressPostalCode] [nvarchar](11) NULL,
	[BusinessAddressState] [nvarchar](50) NULL,
	[BusinessFax] [nvarchar](51) NULL,
	[BusinessHomePage] [nvarchar](51) NULL,
	[BusinessPhone] [nvarchar](30) NULL,
	[BusinessPhoneTwo] [nvarchar](30) NULL,
	[CallBack] [nvarchar](50) NULL,
	[CarPhone] [nvarchar](51) NULL,
	[Children] [varchar](300) NULL,
	[Companies] [nvarchar](350) NULL,
	[CompanyMainPhone] [nvarchar](51) NULL,
	[CompanyName] [nvarchar](350) NULL,
	[CompleteName] [nvarchar](350) NULL,
	[ContactSource] [nvarchar](250) NULL,
	[Department] [nvarchar](250) NULL,
	[DirectoryId] [nvarchar](max) NULL,
	[DirectReports] [nvarchar](max) NULL,
	[EmailAddress1] [nvarchar](max) NULL,
	[EmailAddress2] [nvarchar](max) NULL,
	[EmailAddress3] [nvarchar](max) NULL,
	[EmailAddresses] [nvarchar](max) NULL,
	[FileAs] [nvarchar](max) NULL,
	[FileAsMapping] [nvarchar](max) NULL,
	[Generation] [nvarchar](250) NULL,
	[GivenName] [nvarchar](250) NULL,
	[HasPicture] [nvarchar](max) NULL,
	[HomeAddressCity] [nvarchar](200) NULL,
	[HomeAddressCountryOrRegion] [nvarchar](200) NULL,
	[HomeAddressPostalCode] [nvarchar](51) NULL,
	[HomeAddressState] [nvarchar](50) NULL,
	[HomeAddressStreet] [nvarchar](200) NULL,
	[HomeFax] [nvarchar](31) NULL,
	[HomePhone] [nvarchar](31) NULL,
	[HomePhone2] [nvarchar](31) NULL,
	[ImAddress1] [nvarchar](250) NULL,
	[ImAddress2] [nvarchar](250) NULL,
	[ImAddress3] [nvarchar](250) NULL,
	[ImAddresses] [nvarchar](200) NULL,
	[Isdn] [nvarchar](max) NULL,
	[JobTitle] [nvarchar](400) NULL,
	[Manager] [nchar](200) NULL,
	[ManagerMailbox] [nvarchar](200) NULL,
	[MiddleName] [nvarchar](200) NULL,
	[Mileage] [nvarchar](15) NULL,
	[MobilePhone] [nvarchar](31) NULL,
	[NickName] [nvarchar](200) NULL,
	[Notes] [nvarchar](max) NULL,
	[OfficeLocation] [nvarchar](400) NULL,
	[OtherAddressCity] [nvarchar](400) NULL,
	[OtherAddressCountryOrRegion] [nvarchar](400) NULL,
	[OtherAddressPostalCode] [nvarchar](31) NULL,
	[OtherAddressState] [nvarchar](50) NULL,
	[OtherFax] [nvarchar](31) NULL,
	[OtherTelephone] [nvarchar](31) NULL,
	[Pager] [nvarchar](50) NULL,
	[PhoneNumbers] [nvarchar](30) NULL,
	[PhoneticFirstName] [nvarchar](200) NULL,
	[PhoneticFullName] [nvarchar](200) NULL,
	[PhoneticLastName] [nvarchar](200) NULL,
	[Photo] [nvarchar](max) NULL,
	[PhysicalAddresses] [nvarchar](max) NULL,
	[PhysicalAddressIndex] [nvarchar](max) NULL,
	[PrimaryPhone] [nvarchar](30) NULL,
	[Profession] [nvarchar](200) NULL,
	[RadioPhone] [nvarchar](31) NULL,
	[SpouseName] [nvarchar](200) NULL,
	[Surname] [nvarchar](200) NULL,
	[Telex] [nvarchar](50) NULL,
	[TtyTddPhone] [nvarchar](50) NULL,
	[WeddingAnniversary] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

